// ============================================================================
// Supabase Database Types
//
// This file will be auto-generated by: npx supabase gen types typescript
// Placeholder below matches the schema in supabase/migrations/20260211_001_initial_schema.sql
// ============================================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string;
          avatar_url: string | null;
          is_site_admin: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name: string;
          avatar_url?: string | null;
          is_site_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string;
          avatar_url?: string | null;
          is_site_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      invites: {
        Row: {
          id: string;
          code: string;
          created_by: string;
          claimed_by: string | null;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          created_by: string;
          claimed_by?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          created_by?: string;
          claimed_by?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
      };
      groups: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          invite_code: string;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          invite_code: string;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          invite_code?: string;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      group_members: {
        Row: {
          group_id: string;
          user_id: string;
          role: string;
          joined_at: string;
        };
        Insert: {
          group_id: string;
          user_id: string;
          role?: string;
          joined_at?: string;
        };
        Update: {
          group_id?: string;
          user_id?: string;
          role?: string;
          joined_at?: string;
        };
      };
      draft_proposals: {
        Row: {
          id: string;
          group_id: string;
          proposed_by: string;
          title: string;
          format: string;
          set_code: string | null;
          set_name: string | null;
          cube_id: string | null;
          player_count: number;
          scheduled_at: string | null;
          status: string;
          config: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          proposed_by: string;
          title: string;
          format: string;
          set_code?: string | null;
          set_name?: string | null;
          cube_id?: string | null;
          player_count: number;
          scheduled_at?: string | null;
          status?: string;
          config?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          proposed_by?: string;
          title?: string;
          format?: string;
          set_code?: string | null;
          set_name?: string | null;
          cube_id?: string | null;
          player_count?: number;
          scheduled_at?: string | null;
          status?: string;
          config?: Json | null;
          created_at?: string;
        };
      };
      proposal_votes: {
        Row: {
          proposal_id: string;
          user_id: string;
          vote: string;
          voted_at: string;
        };
        Insert: {
          proposal_id: string;
          user_id: string;
          vote: string;
          voted_at?: string;
        };
        Update: {
          proposal_id?: string;
          user_id?: string;
          vote?: string;
          voted_at?: string;
        };
      };
      drafts: {
        Row: {
          id: string;
          proposal_id: string | null;
          group_id: string;
          host_id: string;
          format: string;
          set_code: string | null;
          set_name: string | null;
          status: string;
          config: Json;
          state: Json | null;
          result: Json | null;
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          proposal_id?: string | null;
          group_id: string;
          host_id: string;
          format: string;
          set_code?: string | null;
          set_name?: string | null;
          status?: string;
          config?: Json;
          state?: Json | null;
          result?: Json | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          proposal_id?: string | null;
          group_id?: string;
          host_id?: string;
          format?: string;
          set_code?: string | null;
          set_name?: string | null;
          status?: string;
          config?: Json;
          state?: Json | null;
          result?: Json | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
      };
      draft_players: {
        Row: {
          draft_id: string;
          user_id: string;
          seat_position: number | null;
          joined_at: string;
        };
        Insert: {
          draft_id: string;
          user_id: string;
          seat_position?: number | null;
          joined_at?: string;
        };
        Update: {
          draft_id?: string;
          user_id?: string;
          seat_position?: number | null;
          joined_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
