-- ============================================================================
-- podman Seed
-- ============================================================================
--
-- Intentionally empty.
--
-- This file used to bootstrap a row in `public.invites` (the old signup gate).
-- That table was dropped by 20260214000100_group_invite_links.sql, so the seed
-- failed with `relation "public.invites" does not exist` and took
-- `npx supabase start` down with it.
--
-- Signup is no longer gated by an invite code — groups are joined through
-- time-limited invite links (`group_invites` + `accept_group_invite`), which
-- are created from the app by a group admin. There is nothing left to seed.
--
-- The integration suites create their own fixtures at runtime against a
-- freshly started stack (see docs/testing.md), so keep this file free of test
-- data: anything added here has to be safe for every developer's local DB.
-- ============================================================================
